s3_conf:
  s3_bucket: test-sairam-test

mysql_conf:
  dbtable: testdb.TRANSACTIONSYNC
  partition_column: App_Transaction_Id
  query : "(select * from testdb.TRANSACTIONSYNC where Internal_Member_Id = 'PC7135361') as t"