source_list:
  - ADDR
  - CP

s3_conf:
  s3_bucket: test-sairam-test
  staging_dir: staging

SB:
  mysql_conf:
    dbtable: testdb.TRANSACTIONSYNC
    partition_column: App_Transaction_Id
    query : "(select * from testdb.TRANSACTIONSYNC where Internal_Member_Id = 'PC7135361') as t"

OL:
  sftp_conf:
      filetype: csv
      delimiter: |
      directory: /home/ubuntu/data

ADDR:
  mongodb_config:
      database: customers
      collection: address
CP:
  filename: KC_Extract_1_20171009.csv
